name: build

on:
  pull_request:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - amazonlinux2
          - centos7
          - almalinux8
          - rockylinux8
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v3
      - name: build
        run: |
          make ${{ matrix.distribution }}
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: test
        run: |
          make test-${{ matrix.distribution }}
        env:
          PLATFORM: ${{ matrix.platform }}

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::445285296882:role/rpm-repository-users-H2ORole-MUDL8E8BJ1VS
          role-session-tagging: true
      - name: upload
        if: github.event_name == 'release'
        run: |
          make upload
